grpc:
  host: "0.0.0.0"
  port: 5001
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8080

log:
  level: debug
  file_path: ./logs/ceramicraft-commodity-mservice.log

mysql:
  host: "127.0.0.1" # mysql-container 127.0.0.1
  port: "3306"
  userName: "root"
  dbName: "product_db"

s3Config:
  bucket_name: "ceramicraft"
  region: "ap-southeast-1"