definitions:
  data.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      err_msg:
        type: string
    type: object
  types.ProductInfo:
    properties:
      capacity:
        type: string
      care_instructions:
        type: string
      category:
        type: string
      desc:
        type: string
      dimensions:
        type: string
      material:
        type: string
      name:
        type: string
      pic_info:
        type: string
      price:
        type: integer
      status:
        description: '0: 未上架, 1: 已上架'
        type: integer
      stock:
        type: integer
      weight:
        type: string
    type: object
  types.UpdateProductStatusRequest:
    properties:
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /add:
    post:
      consumes:
      - application/json
      description: 新增一个商品
      parameters:
      - description: 商品信息
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.ProductInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: 添加商品
      tags:
      - 商品
  /product/{id}:
    get:
      consumes:
      - application/json
      description: 根据商品ID获取商品详细信息
      parameters:
      - description: 商品ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.ProductInfo'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "404":
          description: 商品不存在
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: 获取商品详情
      tags:
      - 商品
  /publish:
    post:
      consumes:
      - application/json
      description: 将商品状态更改为上架状态
      parameters:
      - description: 商品上架请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.UpdateProductStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 上架成功
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "404":
          description: 商品不存在
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: 上架商品
      tags:
      - 商品
  /unpublish:
    post:
      consumes:
      - application/json
      description: 将商品状态更改为下架状态
      parameters:
      - description: 商品下架请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.UpdateProductStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 下架成功
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "404":
          description: 商品不存在
          schema:
            $ref: '#/definitions/data.BaseResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/data.BaseResponse'
      summary: 下架商品
      tags:
      - 商品
swagger: "2.0"
